# Generated by Django 5.0.6 on 2024-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thyroid',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('treatment', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('thyroid_status', models.CharField(blank=True, max_length=3, null=True, unique=True)),
            ],
        ),
    ]
