# Generated by Django 5.0.6 on 2024-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0002_remove_thyroid_thyroid_status_thyroid_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thyroid',
            name='status',
        ),
        migrations.AddField(
            model_name='thyroid',
            name='thyroid_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ("don't know", "Don't Know")], default="Don't Know", max_length=10),
        ),
        migrations.AlterField(
            model_name='thyroid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thyroid',
            name='treatment',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='thyroid',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
