# Generated by Django 5.0.6 on 2024-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0003_remove_thyroid_status_thyroid_thyroid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyroid',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
