# Generated by Django 5.0.6 on 2024-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0004_alter_thyroid_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thyroid',
            old_name='treatment',
            new_name='treatment_status',
        ),
        migrations.AlterField(
            model_name='thyroid',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
