# Generated by Django 5.0.6 on 2024-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0005_rename_treatment_thyroid_treatment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyroid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
