# Generated by Django 5.0.6 on 2024-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0006_alter_thyroid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyroid',
            name='treatment_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ("don't know", "Don't Know")], default='N/A', max_length=10),
        ),
    ]
