# Generated by Django 5.0.6 on 2024-07-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0008_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('on_thyroxine', models.BooleanField()),
                ('query_on_thyroxine', models.BooleanField()),
                ('on_antithyroid_meds', models.BooleanField()),
                ('sick', models.BooleanField()),
                ('pregnant', models.BooleanField()),
                ('thyroid_surgery', models.BooleanField()),
                ('I131_treatment', models.BooleanField()),
                ('query_hypothyroid', models.BooleanField()),
                ('query_hyperthyroid', models.BooleanField()),
                ('lithium', models.BooleanField()),
                ('goitre', models.BooleanField()),
                ('tumor', models.BooleanField()),
                ('hypopituitary', models.FloatField()),
                ('psych', models.BooleanField()),
                ('TSH_measured', models.BooleanField()),
                ('TSH', models.FloatField(blank=True, null=True)),
                ('T3_measured', models.BooleanField()),
                ('T3', models.FloatField(blank=True, null=True)),
                ('TT4_measured', models.BooleanField()),
                ('TT4', models.FloatField(blank=True, null=True)),
                ('T4U_measured', models.BooleanField()),
                ('T4U', models.FloatField(blank=True, null=True)),
                ('FTI_measured', models.BooleanField()),
                ('FTI', models.FloatField(blank=True, null=True)),
                ('TBG_measured', models.BooleanField()),
                ('TBG', models.FloatField(blank=True, null=True)),
                ('referral_source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=50)),
            ],
        ),
    ]
