# Generated by Django 5.0.6 on 2024-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0009_patientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='hypopituitary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='referral_source',
            field=models.CharField(max_length=100),
        ),
    ]
